# Generated by Django 5.1.1 on 2024-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="regno",
            field=models.CharField(default="UNKNOWN", max_length=20, unique=True),
        ),
    ]
